name: icarus
description: Walimurid App

version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  logger: ^2.6.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.3
  riverpod_annotation: ^2.6.1
  go_router: ^16.0.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.2
  table_calendar: ^3.2.0
  android_intent_plus: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.2.1
  permission_handler: ^12.0.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  firebase_analytics: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  mocktail: 1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/clients/default/
    - assets/clients/mancaksa/
    - assets/clients/default/images/
    - assets/clients/mancaksa/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/clients/default/icon.png
  remove_alpha_ios: true
